# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WallApp', '0002_auto_20170223_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, related_name='comments_msg', to='WallApp.Message'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
    ]
