# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginReg', '0002_remove_user_course'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ManyToManyField(related_name='courses', to='loginReg.User'),
        ),
    ]
