# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course',
            new_name='users',
        ),
    ]
